#!/bin/bash
#set -e
set -x
#set -o pipefail

# requres kdialog, gourou, ebook-convert, and mailutils
# programmed by waverider

# PUT YOUR KINDLE EMAIL HERE
EMAIL="user@kindle.com"

# ebook files location
EBOOK="~/ebook"

IN=$(kdialog --getopenfilename $EBOOK '*.acsm')
#NAME=$(kdialog --title "mobiconvert" --inputbox "Export filename?")
NAME=$(echo ${IN%.*})
OUT="$NAME.epub"
DONE="$NAME.mobi"

dbusRef=`kdialog --progressbar "Fullfilling ACSM..." 4`
qdbus $dbusRef showCancelButton true
qdbus $dbusRef Set "" value 1
#until test "true" = `qdbus $dbusRef wasCancelled`; do
  
  STAT=$(acsmdownloader -f $IN -o $OUT)
  ret=$?
  if [ "$ret" == 1 ]
  then
    qdbus $dbusRef close
    kdialog --error "Couldn't fulfill ACSM." "$STAT"
    return
    exit
  fi
  qdbus $dbusRef setLabelText "Cleaning DRM..."
  qdbus $dbusRef Set "" value 2
  STAT=$(adept_remove $OUT)
  ret=$?
  if [ "$ret" != 0 ]
  then
    qdbus $dbusRef close
    kdialog --error "Couldn't remove DRM." "$STAT"
    return 2
    exit
  fi
  qdbus $dbusRef setLabelText "Converting to MOBI..."
  qdbus $dbusRef Set "" value 3
  STAT=$(ebook-convert $OUT $DONE)
  ret=$?
  if [ "$ret" != 0 ]
  then
    qdbus $dbusRef close
    kdialog --error "Couldn't convert to MOBI." "$STAT"
    return 3
    exit
  fi
  qdbus $dbusRef setLabelText "Sending to kindle..."
  qdbus $dbusRef Set "" value 4
  STAT=$(mail -a $DONE -s "book" $EMAIL < /dev/null)
  ret=$?
  if [ "$ret" != 0 ]
  then
    qdbus $dbusRef close
    kdialog --error "Couldn't email to kindle!" "$STAT"
    return 4
    exit
  fi
  echo "Done."
  kdialog --msgbox "Done!\n Finished file is $DONE. \n The book should appear on the kindle soon." 
#done
  qdbus $dbusRef close
